### ISSUE TITLE
can't run example server

### ISSUE THREAD

**Issue by nickdesaulniers** [reqshark/zttp#1]
```
➜  zttp git:(master) node test/zttp.js

ømq endpoint: tcp://127.0.0.1:3000

/Users/Nicholas/code/node/zttp/node_modules/zmq/lib/index.js:190
  this._zmq = new zmq.SocketBinding(defaultContext(), types[type]);
              ^
TypeError: Type must be an integer
    at TypeError (native)
    at new exports.Socket (/Users/Nicholas/code/node/zttp/node_modules/zmq/lib/index.js:190:15)
    at Object.exports.socket.exports.createSocket (/Users/Nicholas/code/node/zttp/node_modules/zmq/lib/index.js:565:14)
    at Object.module.exports.listen (/Users/Nicholas/code/node/zttp/lib/index.js:13:37)
    at Object.<anonymous> (/Users/Nicholas/code/node/zttp/test/zttp.js:1:85)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by reqshark** [comment]
hmm, what version of libzmq do you have?

what prints when you run:

``` bash
$ pkg-config --modversion libzmq
```

**Comment by nickdesaulniers** [comment]
3.2.2

**Comment by reqshark** [comment]
the readme's [install section](https://github.com/reqshark/zttp#install) mentions 4+ is required. update your libzmq.

assuming it was installed using homebrew i always just sweep update everything using: 

```
$ brew update && brew upgrade
```

or do it manually, but rebuild your clone with `npm install` afterwards, maybe run `npm test` too.. 

the example server is just a module exported to `test/index.js` you can tap direct with `node test`.

**Comment by reqshark** [comment]
i think the test passes, updated just now in 94c01d4f950b6

**Comment by reqshark** [comment]
i think this was fixed a while back
